import Head from "next/head";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Informer from "../components/Informer";
import Products from "../components/Products";
import Hero from "../components/Hero";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Lofty home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-auto scrollbar-hide divide-y-2 divide-line/75 ">
        <Navbar />

        <Hero />
        <Products />
        <Informer />
        <Footer />
      </div>
    </div>
  );
}
