import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import { logoutFB } from "../context/slices/sessionSlice";
import { doSignOut } from "../firebase/firebaseAuth";
import Navbar from "../components/Navbar";

import Cookies from "js-cookie";

function Profile() {
  const dispatch = useDispatch();
  const router = useRouter();
  const email = useSelector((state) => state.session.email);

  const handleLogOut = async () => {
    Cookies.remove("session");
    dispatch(logoutFB());
    await doSignOut(email);
    router.push("/");
  };

  return (
    <div className="">
      <Head>
        <title>Lofty profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex flex-col w-full justify-center text-center items-center m-3">
        <h1 className="font-avenir text-heading font-bold my-1 text-5xl">
          Profile
        </h1>
        <p className="font-avenir text-heading font-bold my-1">{email}</p>

        <div className=" my-1 px-6 py-2 leading-5 w-42 text-lg text-background transition-colors text-center duration-200 transform bg-icon rounded-md hover:bg-heading/80 focus:outline-none  font-avenir focus:bg-gray-600">
          <button onClick={() => router.push("/reset_password")}>
            Change password
          </button>
        </div>
        <div className=" my-1 px-6 py-2 leading-5 w-42 text-lg text-background transition-colors text-center duration-200 transform bg-negative rounded-md hover:bg-heading/80 focus:outline-none  font-avenir focus:bg-gray-600">
          <button onClick={handleLogOut}>Cerrar sesion</button>
        </div>
      </div>
    </div>
  );
}

export default Profile;

export async function getServerSideProps({ req, res }) {
  //Quiero obtener el token de las cookies para saber si tengo permiso o redirijo a login

  const token = req.cookies.session;

  if (!token) {
    res.writeHead(302, { Location: "/login" });
    res.end();
  }

  return {
    props: {},
  };
}
