import Head from "next/head";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Products from "../components/Products";
import Hero from "../components/Hero";

export default function Register() {
  return (
    <div>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Products />

      <Footer />
    </div>
  );
}
