import React, { useState } from "react";
import { doSendPasswordResetEmail, doSignOut } from "../firebase/firebaseAuth";
import { useRouter } from "next/router";
import toast, { Toaster } from "react-hot-toast";
import Image from "next/image";
import Head from "next/head";
import Navbar from "../components/Navbar";

function Reset_password() {
  const [email, setEmail] = useState("");
  const router = useRouter();

  const sendLink = async () => {
    if (email) {
      toast.success("Successfully");
      doSendPasswordResetEmail(email);
      Cookies.remove("session");
      dispatch(logoutFB());
      await doSignOut(email);
      router.push("/");
    } else {
      toast.error("Enter your email");
    }
  };

  return (
    <>
      <Head>
        <title>Membership</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className="bg-white dark:bg-gray-800 mx-auto">
        <div className="max-w-3xl px-6 py-16 mx-auto text-center flex flex-col justify-center items-center">
          <h1 className="text-3xl font-semibold text-gray-800 dark:text-gray-100">
            Forgot your password?
          </h1>
          <p className="max-w-md mx-auto mt-5 text-gray-500 dark:text-gray-400">
            Insert into the input your email and we send you reset password link
          </p>

          <div className="flex flex-col mt-8 space-y-3 sm:space-y-0 sm:flex-row sm:justify-center sm:-mx-2">
            <input
              id="email"
              type="text"
              className="px-4 py-2 text-gray-700 bg-white border rounded-md sm:mx-2 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 dark:focus:border-blue-300 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40"
              placeholder="Email Address"
              value={email}
              onChange={(e) => {
                setEmail(e.target.value);
              }}
            />

            <button
              className="my-1 px-6 py-2 leading-5 w-42 text-lg text-background transition-colors text-center duration-200 transform bg-icon rounded-md hover:bg-heading/80 focus:outline-none  font-avenir focus:bg-gray-600"
              onClick={() => sendLink()}
            >
              Send email
            </button>
          </div>
        </div>
        <div>
          <Toaster position="top-center" reverseOrder={false} />
        </div>
      </section>
    </>
  );
}

export default Reset_password;
