import Head from "next/head";
import Navbar from "../components/Navbar";
import ViewPlans from "../components/SelectionSteps/ViewPlans";
import ImagesGallery from "../components/ImagesGallery";
import KeyFeatures from "../components/SelectionSteps/KeyFeatures";
import Colour from "../components/SelectionSteps/Colour";
import Purchase from "../components/SelectionSteps/Purchase";
import AboutAs from "../components/SelectionSteps/AboutAs";
import TopBannerIndex from "../components/TopBanner";
import { useEffect, useState } from "react";

const data = [
  {
    title: "Workspaces",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officiis error officia earum dolor voluptatum delectus corporis, recusandae!",
    image:
      "https://images.unsplash.com/photo-1494173853739-c21f58b16055?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fHdvcmtzcGFjZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    title: "Restaurants",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officiis error officia earum dolor voluptatum delectus corporis, recusandae!",
    image:
      "https://images.unsplash.com/photo-1565895405127-481853366cf8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8ZGluaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    title: "Units",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officiis error officia earum dolor voluptatum delectus corporis, recusandae!",
    image:
      "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGJ1aWxkaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  },
];

export default function SelectionSteps() {
  const [formInformation, setFormInformation] = useState({
    lotNumber: 0,
    price: 0,
    deposit: 0,
    colorPallete: "",
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormInformation((prevState) => ({
      ...prevState,
      [name]: value,
    }));
  };

  return (
    <div className="">
      <Head>
        <title>Selection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-auto scrollbar-hide divide-y-2 divide-line/75 ">
        <Navbar />
        <TopBannerIndex />
        <ViewPlans />
        <ImagesGallery />
        <KeyFeatures />
        <Colour />
        <Purchase />
        <AboutAs />
      </div>
    </div>
  );
}
