import AboutAs from '../../components/SelectionSteps/AboutAs';
import Colour from '../../components/SelectionSteps/Colour';
import Head from 'next/head';
import ImagesGallery from '../../components/Images/ImagesGallery';
import KeyFeatures from '../../components/SelectionSteps/KeyFeatures';
import Navbar from '../../components/Navigation/Navbar';
import Purchase from '../../components/SelectionSteps/Purchase';
import TopBanner from '../../components/Images/TopBanner';
import ViewPlans from '../../components/SelectionSteps/ViewPlans';

export default function SelectionSteps() {
  return (
    <div className="">
      <Head>
        <title>Selection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-auto divide-y-2 scrollbar-hide divide-line/75 ">
        <Navbar />
        <TopBanner urlVideo={'../videoIndexPage.mp4'} />
        <ViewPlans />
        <ImagesGallery />
        <KeyFeatures />
        <Colour />
        <Purchase />
        <AboutAs />
      </div>
    </div>
  );
}
